[2024-11-13 18:18:32,359] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://172.16.237.238:8000
[2024-11-13 18:18:32,359] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-11-13 18:18:38,875] 97 werkzeug - INFO - 172.16.237.238 - - [13/Nov/2024 18:18:38] "GET /predict HTTP/1.1" 200 -
[2024-11-13 18:18:47,213] 97 werkzeug - INFO - 172.16.237.238 - - [13/Nov/2024 18:18:47] "GET /predict HTTP/1.1" 200 -
[2024-11-13 18:19:12,467] 64 root - INFO - Dataframe Gathered..!
[2024-11-13 18:19:12,847] 1414 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\AI-839\MLOps\projects2\FirstMLProject\src\pipeline\prediction_pipeline.py", line 21, in predict
    pred = model.predict(scaled_feature)
AttributeError: 'ColumnTransformer' object has no attribute 'predict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Admin\Downloads\AI-839\MLOps\projects2\FirstMLProject\app.py", line 29, in predict_datapoint
    pred = predict_pipeline.predict(final_data)
  File "C:\Users\Admin\Downloads\AI-839\MLOps\projects2\FirstMLProject\src\pipeline\prediction_pipeline.py", line 25, in predict
    raise customException(e, sys)
src.exceptions.exception.customException: Error occured in python script name [C:\Users\Admin\Downloads\AI-839\MLOps\projects2\FirstMLProject\src\pipeline\prediction_pipeline.py] line number [21] error message ['ColumnTransformer' object has no attribute 'predict']
[2024-11-13 18:19:12,851] 97 werkzeug - INFO - 172.16.237.238 - - [13/Nov/2024 18:19:12] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2024-11-13 18:23:11,450] 64 root - INFO - Dataframe Gathered..!
[2024-11-13 18:23:11,473] 1414 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\AI-839\MLOps\projects2\FirstMLProject\src\pipeline\prediction_pipeline.py", line 21, in predict
    pred = model.predict(scaled_feature)
AttributeError: 'ColumnTransformer' object has no attribute 'predict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Admin\Downloads\AI-839\MLOps\projects2\FirstMLProject\app.py", line 29, in predict_datapoint
    pred = predict_pipeline.predict(final_data)
  File "C:\Users\Admin\Downloads\AI-839\MLOps\projects2\FirstMLProject\src\pipeline\prediction_pipeline.py", line 25, in predict
    raise customException(e, sys)
src.exceptions.exception.customException: Error occured in python script name [C:\Users\Admin\Downloads\AI-839\MLOps\projects2\FirstMLProject\src\pipeline\prediction_pipeline.py] line number [21] error message ['ColumnTransformer' object has no attribute 'predict']
[2024-11-13 18:23:11,480] 97 werkzeug - INFO - 172.16.237.238 - - [13/Nov/2024 18:23:11] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
